spring:
  datasource:
    # Aponta para o túnel do Railway que está rodando em localhost
    url: jdbc:postgresql://localhost:5432/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      # 'update' é seguro para desenvolvimento, pois não apaga dados existentes.
      ddl-auto: update