CREATE TABLE tb_account (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            number VARCHAR(255) UNIQUE NOT NULL,
                            agency VARCHAR(255),
                            balance DECIMAL(13, 2),
                            additional_limit DECIMAL(13, 2)
);

CREATE TABLE tb_card (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         number VARCHAR(255) NOT NULL,
                         available_limit DECIMAL(13, 2)
);

CREATE TABLE tb_feature (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            icon VARCHAR(255),
                            description VARCHAR(255)
);

CREATE TABLE tb_news (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         icon VARCHAR(255),
                         description VARCHAR(255)
);

CREATE TABLE tb_user (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255),
                         account_id BIGINT UNIQUE,
                         card_id BIGINT UNIQUE,
                         CONSTRAINT fk_user_account FOREIGN KEY (account_id) REFERENCES tb_account(id),
                         CONSTRAINT fk_user_card FOREIGN KEY (card_id) REFERENCES tb_card(id)
);

CREATE TABLE tb_user_features (
                                  user_id BIGINT NOT NULL,
                                  feature_id BIGINT NOT NULL,
                                  PRIMARY KEY (user_id, feature_id),
                                  CONSTRAINT fk_user_features_user FOREIGN KEY (user_id) REFERENCES tb_user(id),
                                  CONSTRAINT fk_user_features_feature FOREIGN KEY (feature_id) REFERENCES tb_feature(id)
);

CREATE TABLE tb_user_news (
                              user_id BIGINT NOT NULL,
                              news_id BIGINT NOT NULL,
                              PRIMARY KEY (user_id, news_id),
                              CONSTRAINT fk_user_news_user FOREIGN KEY (user_id) REFERENCES tb_user(id),
                              CONSTRAINT fk_user_news_news FOREIGN KEY (news_id) REFERENCES tb_news(id)
);
